baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
relativeURLS=true
googleAnalytics = "G-Y6X6QFNNHQ"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = ""

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  favicon = "/favicon.ico"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  oneHeadingSize = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Priom Chowdhury"
    subtitle = "Blockchain|Dev|ChainSafe"
    owner = "priom"
    keywords = "priom, chainafe, blockchain, devops, developer, web3, decentralized systesm, distributed systems, toronto, canada"
    copyright = "All Rights Reserved by Priom"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "PRIOM"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "About"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/priom"
      [[languages.en.menu.main]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/pri0m"
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://linkedin.com/in/priomchowdhury"