name: IPFS Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: IPFS Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        env:
          IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.PINATA_API_KEY }}
          IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.PINATA_API_SECRET }}
          IPFS_DEPLOY_CLOUDFLARE__API_EMAIL: ${{ secrets.CF_API_EMAIL }}
          IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          IPFS_DEPLOY_CLOUDFLARE__ZONE: ${{ secrets.CF_ZONE }}
          IPFS_DEPLOY_CLOUDFLARE__RECORD: ${{ secrets.CF_RECORD }}
      - run: npx ipfs-deploy public/ -p pinata -d cloudflare
